custom_paginate:
  main:
    posts_per_page: 3
    path: paginates/main:num.html
    html_path: htmlPaginates/main:num.html

tabs:
  tab_path: assets/tabs/tab-:name.svg
  tab_template: theme/tab.svg
  item_path: assets/tabs/item-:tab-:name.svg
  item_template: theme/listitem.svg
  
  items:
    Blog:
      link: /index.html
    Projects:
      link: /projects/index.html
      items:
        spc:
          link: /projects/spc.html
        Wave Demo:
          link: /projects/wavedemo/index.html
        Minion Army:
          link: /projects/LD33/run.html
        Color Shape Stack:
          link: /projects/LD35/view.html
        Camp Fire Simulator 2016:
          link: /projects/LD36/view.html
        Turtle Fork:
          link: /projects/LD37/view.html
    About:
      link: /about.html

jekyll-press:
    exclude: '/projects/LD33/scripts/canvg/svgs/**'
    js_options: {}
    css_options: {}
    html_options: {}
    enabled: false

ignore-file:
    exclude: '**/svgo.yml'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      
collections:
  posts:
    output: true
    permalink: posts//:categories/:year/:month/:day/:title.html