custom_paginate:
  main:
    posts_per_page: 3
    path: paginates/main:num.html
    html_path: htmlPaginates/main:num.html

tabs:
  tab_path: assets/tabs/tab-:name.svg
  tab_template: theme/tab.svg
  item_path: assets/tabs/item-:tab-:name.svg
  item_template: theme/listitem.svg
  
  items:
    Blog:
      link: /index.html
    Projects:
      link: /projects/index.html
      items:
        spc:
          link: /projects/spc.html
        Wave Demo:
          link: /projects/wavedemo/index.html
        Shadows and Lights:
          link: /projects/LD30/index.html
        Minion Army:
          link: /projects/LD33/view.html
        Color Shape Stack:
          link: /projects/LD35/view.html
        Camp Fire Simulator 2016:
          link: /projects/LD36/view.html
        Turtle Fork:
          link: /projects/LD37/view.html
        Planet Carbalsnahps 2:
          link: /projects/LD38/view.html
        Ludum Dare 42:
          link: /projects/LD42/view.html
    About:
      link: /about.html

jekyll-press:
    js_options: {}
    css_options: {}
    html_options: {}
    enabled: false

ignore-file:
    exclude:
      - '**/svgo.yml'
      - '/Gemfile'
      - '/Gemfile.lock'
      - '/runServer.bat'
      - '/package.json'
      - '/setup'

output-build:
  -
    dir: '_repos/Ludum-Dare-33'
    cmd: 'npm install & grunt build'
    build: 'build/release'
    output: 'projects/LD33'
    exclude: '**/node_modules/**'
  -
    dir: '_repos/Ludum-Dare-35'
    cmd: 'npm install & grunt build'
    build: 'build/release'
    output: 'projects/LD35'
    exclude: '**/node_modules/**'
  -
    dir: '_repos/Ludum-Dare-36'
    cmd: 'npm install & grunt build'
    build: 'build/release'
    output: 'projects/LD36'
    exclude: '**/node_modules/**'
  -
    dir: '_repos/Ludum-Dare-37'
    cmd: 'npm install & grunt build'
    build: 'build/release'
    output: 'projects/LD37'
    exclude: '**/node_modules/**'
  -
    dir: '_repos/Ludum-Dare-38'
    cmd: 'npm install & gulp build'
    build: 'build/release'
    output: 'projects/LD38'
    exclude: '**/node_modules/**'
  -
    dir: '_repos/Ludum-Dare-42'
    cmd: 'npm install & gulp build'
    build: 'build/release'
    output: 'projects/LD42'
    exclude: '**/node_modules/**'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      
collections:
  posts:
    output: true
    permalink: posts//:categories/:year/:month/:day/:title.html