custom_paginate:
  main:
    posts_per_page: 3
    path: indexes/main:num.html
    html_path: htmlindex/main:num.html

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      
collections:
  posts:
    output: true
    permalink: posts//:categories/:year/:month/:day/:title.html